import { Link } from 'react-router-dom'
import { Icon } from '../../components/ui'

export function TermsPage() {
  return (
    <main className="flex-1 w-full pb-16">
      <div className="container-max px-4 md:px-8 py-8">
        <nav className="flex items-center gap-2 text-xs font-mono text-(--text-secondary) mb-6">
          <Link to="/" className="hover:text-(--text-primary) transition-colors">HOME</Link>
          <Icon name="chevron_right" size={12} />
          <span className="text-(--accent-blue)">TERMS OF SERVICE</span>
        </nav>

        <header className="mb-10 border-b border-(--border-theme) pb-6">
          <h1 className="text-(--text-primary) font-sans font-bold text-3xl md:text-4xl tracking-tight mb-3">
            Terms of Service & Sales Agreement
          </h1>
          <p className="text-(--text-secondary) text-sm max-w-2xl leading-relaxed">
            Please read these terms carefully before placing orders or building custom PC configurations on PREMIUM PC.
          </p>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 font-sans">
          <div className="lg:col-span-8 space-y-8 text-sm text-(--text-secondary) leading-relaxed">
            <section className="space-y-3">
              <h2 className="text-(--text-primary) font-bold text-xl tracking-tight">1. Product Pricing & Stock Availability</h2>
              <p>
                All prices shown are subject to manufacturer availability and market fluctuations. We reserve the right to correct typographical pricing errors before order processing.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-(--text-primary) font-bold text-xl tracking-tight">2. Custom PC Building Terms</h2>
              <p>
                Custom PC orders enter bench testing within 24 hours of confirmation. Compatibility warnings generated by the PC Builder tool serve as technical guidance.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-(--text-primary) font-bold text-xl tracking-tight">3. Legal Business Entity</h2>
              <div className="p-4 bg-(--bg-surface-secondary) border border-(--border-theme) rounded-xl text-xs font-mono space-y-1 text-(--text-secondary)">
                <div><span className="text-(--text-primary) font-semibold">Corporate Operator:</span> [CLIENT CONFIRMATION REQUIRED: Legal Company Name]</div>
                <div><span className="text-(--text-primary) font-semibold">Registration / Tax ID:</span> [CLIENT CONFIRMATION REQUIRED: Tax Registration Number]</div>
                <div><span className="text-(--text-primary) font-semibold">Jurisdiction:</span> [CLIENT CONFIRMATION REQUIRED: Governing State/Country Law]</div>
              </div>
            </section>
          </div>

          <aside className="lg:col-span-4">
            <div className="bg-(--bg-surface) border border-(--border-theme) rounded-xl p-6 space-y-4 sticky top-24">
              <h3 className="text-(--text-primary) font-bold text-base flex items-center gap-2">
                <Icon name="gavel" size={18} className="text-(--accent-blue)" />
                Legal Questions?
              </h3>
              <p className="text-xs text-(--text-secondary) leading-relaxed">
                Contact our customer compliance team for legal or terms-related inquiries.
              </p>
              <Link to="/support" className="text-(--accent-blue) font-sans text-xs font-semibold hover:underline block pt-1">
                Contact Support Portal →
              </Link>
            </div>
          </aside>
        </div>
      </div>
    </main>
  )
}
